### ISSUE TITLE
Extracting numbers from string is not working for double digits and more.

### ISSUE THREAD

**Issue by SarmGit** [ProstDev/getting-to-the-point#1]
extract-digits-from-string-dw2.txt

{
    "message": "Json content is not compliant with schema.[$[0].msg: integer found, string expected, $[22].msg: integer found, string expected, $[44].msg: integer found, string expected]"
}

gives output -
"0,2,2,4,4"

Instead of giving
"0,22,44"

Suggest a solution

**Comment by alexandramartinez** [comment]
can you share the input you're using?

**Comment by alexandramartinez** [comment]
if I try the input from the example, it works as expected. So, I need to know what input you're using for your example

![image](https://github.com/ProstDev/getting-to-the-point/assets/3922764/5b25e7bd-d4b1-4335-a462-93a38ae52c5e)

**Comment by SarmGit** [comment]
I need to extract the number from the payload so that i can know in which places exactly the failures are happening in the validator.

Input - 
{
    "message": "Json content is not compliant with schema.[[0].msg: integer found, string expected, [22].msg: integer found, string expected, [4].msg: integer found, string expected]"
}

%dw 2.0
output application/json
---
flatten (payload.message scan /\d/) joinBy ","

Output -
"0,2,2,4"

I want the answer to be "0,22,4"

Since you are using joinBy "" it works but if you use joinBy "," it will separate 1,2,3 .

I tried this and it worked - 
%dw 2.0
output application/json
---
flatten (payload.message scan /\d+/) joinBy ","

Using a + after d seems to pick multiple digits .

Let me know if this helps.

**Comment by alexandramartinez** [comment]
Ohh I see what you mean. The regex I used was supposed to retrieve all numbers separately (by digits). So, if you do 

```dataweave
flatten(payload.message scan /\d/)
```

it will return the array of **each** digit separately. Like this:

```json
[
  "0",
  "2",
  "2",
  "4"
]
```

so, of course when you then use `joinBy`, it will join each digit.

Since your requirement is to get each number that's not separated by digit, then you'd require a different regex. As you found out, `d+` would give you exactly that. Whereas `d` would give you each digit.

So, in that case, when you do `flatten(payload.message scan /\d+/)`, you end up with a different array:

```json
[
  "0",
  "22",
  "4"
]
```

that's why when you use `joinBy`, you are able to separate the 22 accordingly.
